"""
Verified, high-fidelity sample data representing Hollywood's most viral Blockbusters,
Legendary TV Series, and Cult Franchises with 100% authentic, verified 200 OK TMDB images.
Includes high-CTR hook titles and catchy teasers for maximum engagement.
"""

SAMPLE_MEDIA = [
    # 1. Money Heist (La Casa de Papel)
    {
        "id": 71446,
        "title": "Money Heist",
        "original_title": "La Casa de Papel",
        "slug": "money-heist",
        "media_type": "tv",
        "release_date": "2017-05-02",
        "hook_title": "Bella Ciao! 5 Insane Professor Masterstrokes You Missed 💰",
        "catchy_teaser": "1 Mastermind. 67 hostages. €2.4 Billion printed. Can you predict the Professor's next move?",
        "overview": "Eight robbers lock themselves in the Royal Mint of Spain with hostages, executing the greatest heist in human history planned by a criminal genius.",
        "tagline": "The heist was just the beginning.",
        "genres": ["Crime", "Drama", "Thriller"],
        "runtime": 50,
        "seasons": 5,
        "vote_average": 8.2,
        "vote_count": 18500,
        "category": "series",
        "director": "Álex Pina",
        "top_cast": ["Álvaro Morte", "Úrsula Corberó", "Pedro Alonso", "Itziar Ituño", "Alba Flores"],
        "poster_path": "/reEMJA1uzscCbkpeRJeTT2bjqUp.jpg",
        "backdrop_path": "/gFZriCkpJYsApPZEF3jhxL4yLzG.jpg",
        "backdrops": [
            "/gFZriCkpJYsApPZEF3jhxL4yLzG.jpg",
            "/reEMJA1uzscCbkpeRJeTT2bjqUp.jpg"
        ]
    },
    # 2. Final Destination
    {
        "id": 9532,
        "title": "Final Destination",
        "original_title": "Final Destination",
        "slug": "final-destination",
        "media_type": "movie",
        "release_date": "2000-03-17",
        "hook_title": "Death's Plan: 5 Terrifying Accidental Kill Traps Ranked 💀",
        "catchy_teaser": "No matter where you hide, Death is already waiting in the shadows. Discover the sinister rules!",
        "overview": "After a teenager cheats death by fleeing an exploding airplane, Grim Reaper stalks the survivors with brutal chain-reaction accidents.",
        "tagline": "Death doesn't like to be cheated.",
        "genres": ["Horror", "Mystery"],
        "runtime": 98,
        "seasons": None,
        "vote_average": 6.6,
        "vote_count": 5200,
        "category": "cult_classic",
        "director": "James Wong",
        "top_cast": ["Devon Sawa", "Ali Larter", "Kerr Smith", "Tony Todd"],
        "poster_path": "/1mXhlQMnlfvJ2frxTjZSQNnA9Vp.jpg",
        "backdrop_path": "/7isarjYDEKZ5t1CgcvbuqEUby8P.jpg",
        "backdrops": [
            "/7isarjYDEKZ5t1CgcvbuqEUby8P.jpg",
            "/1mXhlQMnlfvJ2frxTjZSQNnA9Vp.jpg"
        ]
    },
    # 3. Stranger Things
    {
        "id": 66732,
        "title": "Stranger Things",
        "original_title": "Stranger Things",
        "slug": "stranger-things",
        "media_type": "tv",
        "release_date": "2016-07-15",
        "hook_title": "The Upside Down: 5 Dark Secrets Ahead Of Season 5 🚲⚡",
        "catchy_teaser": "Hawkins will never be the same. 5 chilling Upside Down mysteries before the epic series finale!",
        "overview": "When a young boy vanishes, a small town uncovers a supernatural underworld of secret lab experiments and telekinetic girl Eleven.",
        "tagline": "Every ending has a beginning.",
        "genres": ["Sci-Fi & Fantasy", "Drama", "Mystery"],
        "runtime": 60,
        "seasons": 4,
        "vote_average": 8.6,
        "vote_count": 17200,
        "category": "series",
        "director": "The Duffer Brothers",
        "top_cast": ["Millie Bobby Brown", "Finn Wolfhard", "Winona Ryder", "David Harbour", "Sadie Sink"],
        "poster_path": "/49WJfeN0moxb9IPfGn8AIqMGskD.jpg",
        "backdrop_path": "/56v2KjBlU4XaOv9rVYEQypROD7P.jpg",
        "backdrops": [
            "/56v2KjBlU4XaOv9rVYEQypROD7P.jpg",
            "/49WJfeN0moxb9IPfGn8AIqMGskD.jpg"
        ]
    },
    # 4. The Boys
    {
        "id": 76479,
        "title": "The Boys",
        "original_title": "The Boys",
        "slug": "the-boys",
        "media_type": "tv",
        "release_date": "2019-07-26",
        "hook_title": "Homelander Unhinged: 5 Sickest Twists In The Boys 🩸🦸‍♂️",
        "catchy_teaser": "What if superheroes were bloodthirsty corporate psychos? Inside Homelander's maddest stunts.",
        "overview": "A vigilante squad embarks on a heroic quest to expose the truth about corrupt superheroes who abuse their godlike powers.",
        "tagline": "Never meet your heroes.",
        "genres": ["Action & Adventure", "Sci-Fi & Fantasy"],
        "runtime": 60,
        "seasons": 4,
        "vote_average": 8.5,
        "vote_count": 10400,
        "category": "series",
        "director": "Eric Kripke",
        "top_cast": ["Karl Urban", "Jack Quaid", "Antony Starr", "Erin Moriarty", "Jensen Ackles"],
        "poster_path": "/in1R2dDc421JxsoRWaIIAqVI2KE.jpg",
        "backdrop_path": "/bq28ajZaoMyzEIm6REelqyqtEDZ.jpg",
        "backdrops": [
            "/bq28ajZaoMyzEIm6REelqyqtEDZ.jpg",
            "/in1R2dDc421JxsoRWaIIAqVI2KE.jpg"
        ]
    },
    # 5. Breaking Bad
    {
        "id": 1396,
        "title": "Breaking Bad",
        "original_title": "Breaking Bad",
        "slug": "breaking-bad",
        "media_type": "tv",
        "release_date": "2008-01-20",
        "hook_title": "I Am The Danger: How Walter White Became TV's Greatest Villain ⚗️",
        "catchy_teaser": "Say his name! How a dying chemistry teacher built a billion-dollar meth empire and lost his soul.",
        "overview": "A chemistry teacher diagnosed with terminal lung cancer teams up with a former student to manufacture crystal meth to secure his family's future.",
        "tagline": "All hail the king.",
        "genres": ["Drama", "Crime"],
        "runtime": 47,
        "seasons": 5,
        "vote_average": 8.9,
        "vote_count": 14900,
        "category": "series",
        "director": "Vince Gilligan",
        "top_cast": ["Bryan Cranston", "Aaron Paul", "Anna Gunn", "Giancarlo Esposito", "Bob Odenkirk"],
        "poster_path": "/anFx9aTOOYqgS3v7x3R84Kz67ly.jpg",
        "backdrop_path": "/tsRy63Mu5cu8etL1X7ZLyf7UP1M.jpg",
        "backdrops": [
            "/tsRy63Mu5cu8etL1X7ZLyf7UP1M.jpg",
            "/anFx9aTOOYqgS3v7x3R84Kz67ly.jpg"
        ]
    },
    # 6. Wednesday
    {
        "id": 119051,
        "title": "Wednesday",
        "original_title": "Wednesday",
        "slug": "wednesday",
        "media_type": "tv",
        "release_date": "2022-11-23",
        "hook_title": "Wednesday Addams: 5 Goth Secrets That Broke Netflix Records 🖤🕷️",
        "catchy_teaser": "Snarky, psychic, and deadly. 5 Nevermore secrets and viral moments that shattered Netflix records!",
        "overview": "Wednesday Addams investigates a monstrous murder spree while mastering her emerging psychic abilities at Nevermore Academy.",
        "tagline": "Smart, sarcastic and a little dead inside.",
        "genres": ["Sci-Fi & Fantasy", "Mystery", "Comedy"],
        "runtime": 50,
        "seasons": 1,
        "vote_average": 8.4,
        "vote_count": 8700,
        "category": "series",
        "director": "Tim Burton",
        "top_cast": ["Jenna Ortega", "Gwendoline Christie", "Emma Myers", "Christina Ricci", "Catherine Zeta-Jones"],
        "poster_path": "/avzWIWe6FWZi7r1qJeQZcDTv3Ex.jpg",
        "backdrop_path": "/iHSwvRVsRyxpX7FE7GbviaDvgGZ.jpg",
        "backdrops": [
            "/iHSwvRVsRyxpX7FE7GbviaDvgGZ.jpg",
            "/avzWIWe6FWZi7r1qJeQZcDTv3Ex.jpg"
        ]
    },
    # 7. Game of Thrones
    {
        "id": 1399,
        "title": "Game of Thrones",
        "original_title": "Game of Thrones",
        "slug": "game-of-thrones",
        "media_type": "tv",
        "release_date": "2011-04-17",
        "hook_title": "Winter Is Here: 5 Shocking Westeros Secrets Finally Unveiled 🐉⚔️",
        "catchy_teaser": "When you play the game of thrones, you win or you die. 5 dark secrets and epic dragon battles!",
        "overview": "Nine noble families fight for control over the lands of Westeros, while an ancient enemy returns after being dormant for millennia.",
        "tagline": "Winter is coming.",
        "genres": ["Sci-Fi & Fantasy", "Drama", "Action & Adventure"],
        "runtime": 60,
        "seasons": 8,
        "vote_average": 8.4,
        "vote_count": 24000,
        "category": "series",
        "director": "David Benioff & D.B. Weiss",
        "top_cast": ["Emilia Clarke", "Kit Harington", "Peter Dinklage", "Lena Headey", "Sophie Turner"],
        "poster_path": "/seGbGCqUI1DzYndRekrpuBQS64k.jpg",
        "backdrop_path": "/zZqpAXxVSBtxV9qPBcscfXBcL2w.jpg",
        "backdrops": [
            "/zZqpAXxVSBtxV9qPBcscfXBcL2w.jpg",
            "/seGbGCqUI1DzYndRekrpuBQS64k.jpg"
        ]
    },
    # 8. Interstellar
    {
        "id": 157336,
        "title": "Interstellar",
        "original_title": "Interstellar",
        "slug": "interstellar",
        "media_type": "movie",
        "release_date": "2014-11-05",
        "hook_title": "Into The Black Hole: 5 Christopher Nolan Mindfucks In Interstellar 🚀⏳",
        "catchy_teaser": "Love bends space and time. Unravel Christopher Nolan's mind-bending black hole puzzle!",
        "overview": "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival beyond a dying Earth.",
        "tagline": "Mankind was born on Earth. It was never meant to die here.",
        "genres": ["Adventure", "Drama", "Science Fiction"],
        "runtime": 169,
        "seasons": None,
        "vote_average": 8.4,
        "vote_count": 35000,
        "category": "cult_classic",
        "director": "Christopher Nolan",
        "top_cast": ["Matthew McConaughey", "Anne Hathaway", "Jessica Chastain", "Michael Caine"],
        "poster_path": "/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg",
        "backdrop_path": "/xJHokMbljvjADYdit5fK5VQsXEG.jpg",
        "backdrops": [
            "/xJHokMbljvjADYdit5fK5VQsXEG.jpg",
            "/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg"
        ]
    },
    # 9. Inception
    {
        "id": 27205,
        "title": "Inception",
        "original_title": "Inception",
        "slug": "inception",
        "media_type": "movie",
        "release_date": "2010-07-15",
        "hook_title": "Did The Top Stop Spinning? 5 Mind-Bending Inception Secrets 🌀💤",
        "catchy_teaser": "Is this reality or dream level 3? Look closely at the spinning top totem before time runs out!",
        "overview": "A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a CEO.",
        "tagline": "Your mind is the scene of the crime.",
        "genres": ["Action", "Science Fiction", "Adventure"],
        "runtime": 148,
        "seasons": None,
        "vote_average": 8.4,
        "vote_count": 36000,
        "category": "cult_classic",
        "director": "Christopher Nolan",
        "top_cast": ["Leonardo DiCaprio", "Joseph Gordon-Levitt", "Elliot Page", "Tom Hardy", "Cillian Murphy"],
        "poster_path": "/xlaY2zyzMfkhk0HSC5VUwzoZPU1.jpg",
        "backdrop_path": "/8ZTVqvKDQ8emSGUEMjsS4yHAwrp.jpg",
        "backdrops": [
            "/8ZTVqvKDQ8emSGUEMjsS4yHAwrp.jpg",
            "/xlaY2zyzMfkhk0HSC5VUwzoZPU1.jpg"
        ]
    },
    # 10. The Dark Knight
    {
        "id": 155,
        "title": "The Dark Knight",
        "original_title": "The Dark Knight",
        "slug": "the-dark-knight",
        "media_type": "movie",
        "release_date": "2008-07-16",
        "hook_title": "Why So Serious? How Heath Ledger's Joker Made Movie History 🃏🦇",
        "catchy_teaser": "Some men just want to watch the world burn. Heath Ledger's unforgettable Joker secrets revealed.",
        "overview": "When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological tests of his ability to fight injustice.",
        "tagline": "Welcome to a world without rules.",
        "genres": ["Action", "Crime", "Drama"],
        "runtime": 152,
        "seasons": None,
        "vote_average": 8.5,
        "vote_count": 33000,
        "category": "cult_classic",
        "director": "Christopher Nolan",
        "top_cast": ["Christian Bale", "Heath Ledger", "Aaron Eckhart", "Michael Caine", "Morgan Freeman"],
        "poster_path": "/qJ2tW6WMUDux911r6m7haRef0WH.jpg",
        "backdrop_path": "/9FE5eD92WfVCiivM9Pq9GVSrlWk.jpg",
        "backdrops": [
            "/9FE5eD92WfVCiivM9Pq9GVSrlWk.jpg",
            "/qJ2tW6WMUDux911r6m7haRef0WH.jpg"
        ]
    },
    # 11. John Wick: Chapter 4
    {
        "id": 603692,
        "title": "John Wick: Chapter 4",
        "original_title": "John Wick: Chapter 4",
        "slug": "john-wick-chapter-4",
        "media_type": "movie",
        "release_date": "2023-03-22",
        "hook_title": "Baba Yaga Returns: 442 Kills & Insane Stunt Secrets Revealed 🔫🥋",
        "catchy_teaser": "442 Kills and non-stop action! How Keanu Reeves survived the ultimate global assassin war.",
        "overview": "With the price on his head ever increasing, John Wick uncovers a path to defeating The High Table, but first must face a new enemy with powerful alliances across the globe.",
        "tagline": "No way back, one way out.",
        "genres": ["Action", "Thriller", "Crime"],
        "runtime": 169,
        "seasons": None,
        "vote_average": 7.7,
        "vote_count": 6400,
        "category": "trending",
        "director": "Chad Stahelski",
        "top_cast": ["Keanu Reeves", "Donnie Yen", "Bill Skarsgård", "Laurence Fishburne", "Hiroyuki Sanada"],
        "poster_path": "/sP7MVWz9Fi5nkLmRCNKXnlcKkdb.jpg",
        "backdrop_path": "/7I6VUdPj6tQECNHdviJkUHD2u89.jpg",
        "backdrops": [
            "/7I6VUdPj6tQECNHdviJkUHD2u89.jpg",
            "/sP7MVWz9Fi5nkLmRCNKXnlcKkdb.jpg"
        ]
    },
    # 12. Deadpool & Wolverine
    {
        "id": 533535,
        "title": "Deadpool & Wolverine",
        "original_title": "Deadpool & Wolverine",
        "slug": "deadpool-and-wolverine",
        "media_type": "movie",
        "release_date": "2024-07-26",
        "hook_title": "Maximum Effort! 5 Mindblowing Marvel Cameos & Secrets ⚔️🍿",
        "catchy_teaser": "The MCU's wildest duo! R-rated carnage, savage fourth-wall roasts, and mind-blowing cameos.",
        "overview": "A listless Wade Wilson toils away in civilian life. But when his homeworld faces an existential threat, Wade reluctantly suits up with an even more reluctant Wolverine.",
        "tagline": "Come together.",
        "genres": ["Action", "Comedy", "Science Fiction"],
        "runtime": 128,
        "seasons": None,
        "vote_average": 7.7,
        "vote_count": 6100,
        "category": "trending",
        "director": "Shawn Levy",
        "top_cast": ["Ryan Reynolds", "Hugh Jackman", "Emma Corrin", "Morena Baccarin", "Matthew Macfadyen"],
        "poster_path": "/v0Q2uYARIqui1sEBF0bCLJaliDI.jpg",
        "backdrop_path": "/by8z9Fe8y7p4jo2YlW2SZDnptyT.jpg",
        "backdrops": [
            "/by8z9Fe8y7p4jo2YlW2SZDnptyT.jpg",
            "/v0Q2uYARIqui1sEBF0bCLJaliDI.jpg"
        ]
    },
    # 13. Dune: Part Two
    {
        "id": 693134,
        "title": "Dune: Part Two",
        "original_title": "Dune: Part Two",
        "slug": "dune-part-two",
        "media_type": "movie",
        "release_date": "2024-03-01",
        "hook_title": "Shai-Hulud Unleashed: 5 Epic Dune 2 Secrets You Missed 🏜️🔥",
        "catchy_teaser": "Ride the colossal sandworms of Arrakis into holy war! 5 mind-blowing secrets from Denis Villeneuve.",
        "overview": "Paul Atreides unites with Chani and the Fremen while on a warpath of revenge against the conspirators who destroyed his family.",
        "tagline": "Long live the fighters.",
        "genres": ["Science Fiction", "Adventure"],
        "runtime": 166,
        "seasons": None,
        "vote_average": 8.2,
        "vote_count": 5400,
        "category": "trending",
        "director": "Denis Villeneuve",
        "top_cast": ["Timothée Chalamet", "Zendaya", "Rebecca Ferguson", "Javier Bardem", "Austin Butler"],
        "poster_path": "/3HzGtM0JpfH2pWFGugJK22LRP6b.jpg",
        "backdrop_path": "/eZ239CUp1d6OryZEBPnO2n87gMG.jpg",
        "backdrops": [
            "/eZ239CUp1d6OryZEBPnO2n87gMG.jpg",
            "/3HzGtM0JpfH2pWFGugJK22LRP6b.jpg"
        ]
    },
    # 14. Gladiator II
    {
        "id": 558449,
        "title": "Gladiator II",
        "original_title": "Gladiator II",
        "slug": "gladiator-ii",
        "media_type": "movie",
        "release_date": "2024-11-22",
        "hook_title": "Echoes In Eternity: Inside Ridley Scott's Epic Colosseum War 🏛️⚔️",
        "catchy_teaser": "What we do in life echoes in eternity. Colosseum warfare returns in Ridley Scott's epic spectacle!",
        "overview": "Years after witnessing the death of hero Maximus, Lucius enters the Colosseum after his home is conquered by the tyrannical Emperors of Rome.",
        "tagline": "What we do in life echoes in eternity.",
        "genres": ["Action", "Adventure", "Drama"],
        "runtime": 148,
        "seasons": None,
        "vote_average": 6.8,
        "vote_count": 2800,
        "category": "upcoming",
        "director": "Ridley Scott",
        "top_cast": ["Paul Mescal", "Pedro Pascal", "Denzel Washington", "Connie Nielsen"],
        "poster_path": "/2cxhvwyEwRlysAmRH4iodkvo0z5.jpg",
        "backdrop_path": "/tOqIwliWMovSIZ9DyvHcHI7p2im.jpg",
        "backdrops": [
            "/tOqIwliWMovSIZ9DyvHcHI7p2im.jpg",
            "/2cxhvwyEwRlysAmRH4iodkvo0z5.jpg"
        ]
    },
    # 15. Weekly Top 10 Streaming Hits (US/UK) - Netflix / HBO / Prime
    {
        "id": 999101,
        "title": "Top 10 Streaming Hits (US & UK)",
        "original_title": "Weekly Streaming Chart Leaderboard",
        "slug": "streaming-weekly-top-10-us-uk",
        "media_type": "tv",
        "release_date": "2026-10-01",
        "hook_title": "Top 10 Streaming Hits This Week in the US & UK 🍿📊",
        "catchy_teaser": "What is everyone watching right now? Netflix, HBO Max & Prime Video leaderboard rankings revealed!",
        "overview": "An authoritative weekly countdown of the 10 most-streamed television shows and movies across Netflix, HBO Max, and Amazon Prime Video in the United States and United Kingdom.",
        "tagline": "The definitive weekly streaming charts.",
        "genres": ["News", "Drama", "Sci-Fi & Fantasy"],
        "runtime": 45,
        "seasons": 2026,
        "vote_average": 8.8,
        "vote_count": 9200,
        "category": "streaming_charts",
        "director": "Streaming Analytics Desk",
        "top_cast": ["Squid Game", "House of the Dragon", "Fallout", "The Boys", "The Penguin"],
        "poster_path": "/8VWU3V1omprZmqk3Jk8EhDvwF6D.jpg",
        "backdrop_path": "/mnUozozJf3VUpgi91ysfyxlRqs1.jpg",
        "backdrops": [
            "/mnUozozJf3VUpgi91ysfyxlRqs1.jpg",
            "/8VWU3V1omprZmqk3Jk8EhDvwF6D.jpg"
        ]
    },
    # 16. Fallout (Prime Video Weekly Sensation)
    {
        "id": 106379,
        "title": "Fallout",
        "original_title": "Fallout",
        "slug": "fallout-prime-video",
        "media_type": "tv",
        "release_date": "2024-04-10",
        "hook_title": "Fallout: 5 Mind-Blowing Vault Secrets That Broke Prime Video ☢️ Vault 33",
        "catchy_teaser": "War never changes. 5 insane Vault-Tec secrets and wasteland survival moments on Prime Video!",
        "overview": "In a future, post-apocalyptic Los Angeles brought about by nuclear decimation, citizens must live in underground subterranean vaults to protect themselves from radiation, mutants, and bandits.",
        "tagline": "Welcome to the wasteland.",
        "genres": ["Sci-Fi & Fantasy", "Action & Adventure", "Comedy"],
        "runtime": 55,
        "seasons": 1,
        "vote_average": 8.3,
        "vote_count": 8900,
        "category": "streaming_charts",
        "director": "Jonathan Nolan & Lisa Joy",
        "top_cast": ["Ella Purnell", "Walton Goggins", "Aaron Moten", "Kyle MacLachlan"],
        "poster_path": "/8zQO5GNWQwJG4we5AYfjopblRFe.jpg",
        "backdrop_path": "/jqrYg35GHuMGwGqEVUthqTLQnay.jpg",
        "backdrops": [
            "/jqrYg35GHuMGwGqEVUthqTLQnay.jpg",
            "/gMZdpavHmxFNnLpMHwVxfqeux2g.png"
        ]
    },
    # 17. House of the Dragon (HBO Max Weekly Chart-Topper)
    {
        "id": 94997,
        "title": "House of the Dragon",
        "original_title": "House of the Dragon",
        "slug": "house-of-the-dragon",
        "media_type": "tv",
        "release_date": "2022-08-21",
        "hook_title": "Dance of the Dragons: 5 Brutal Westeros Clashes On HBO Max 🐉🔥",
        "catchy_teaser": "Blood will be spilled. Inside HBO's record-breaking #1 fantasy war for the Iron Throne!",
        "overview": "The Targaryen dynasty is at the absolute apex of its power, with more than 15 dragons under their yoke. But power turns inward, sparking the legendary Dance of the Dragons civil war.",
        "tagline": "Fire and blood.",
        "genres": ["Sci-Fi & Fantasy", "Drama", "Action & Adventure"],
        "runtime": 60,
        "seasons": 2,
        "vote_average": 8.4,
        "vote_count": 12500,
        "category": "streaming_charts",
        "director": "Ryan J. Condal & George R.R. Martin",
        "top_cast": ["Emma D'Arcy", "Matt Smith", "Olivia Cooke", "Rhys Ifans"],
        "poster_path": "/wcGMvwZjHSIxfFavfZ4OzXbhyG8.jpg",
        "backdrop_path": "/9rJafPDkQP8YuLy9iY5v19ZfMIW.jpg",
        "backdrops": [
            "/9rJafPDkQP8YuLy9iY5v19ZfMIW.jpg",
            "/hRX5exGCfaEq7mLYCqRoKiEkjq3.jpg"
        ]
    },
    # 18. Marvel Multiverse: Post-Credit Theories
    {
        "id": 999201,
        "title": "Marvel Post-Credit Theories",
        "original_title": "Marvel Multiverse & Post-Credits",
        "slug": "marvel-post-credit-theories",
        "media_type": "movie",
        "release_date": "2024-07-26",
        "hook_title": "Marvel Post-Credits: 6 Insane Easter Eggs & Secret Wars Theories 🦸‍♂️⚡",
        "catchy_teaser": "Did you spot the hidden comic cameos? 6 post-credit clues setting up Avengers: Secret Wars!",
        "overview": "Deconstructing the most consequential post-credit stingers in MCU history, from Deadpool's Void reveals and Anchor Beings to Doctor Doom and the road to Avengers: Secret Wars.",
        "tagline": "The end credits are only the beginning.",
        "genres": ["Action", "Science Fiction", "Adventure"],
        "runtime": 120,
        "seasons": None,
        "vote_average": 8.5,
        "vote_count": 14000,
        "category": "theories_easter_eggs",
        "director": "Kevin Feige & Marvel Brain Trust",
        "top_cast": ["Ryan Reynolds", "Hugh Jackman", "Robert Downey Jr.", "Benedict Cumberbatch"],
        "poster_path": "/v0Q2uYARIqui1sEBF0bCLJaliDI.jpg",
        "backdrop_path": "/by8z9Fe8y7p4jo2YlW2SZDnptyT.jpg",
        "backdrops": [
            "/by8z9Fe8y7p4jo2YlW2SZDnptyT.jpg",
            "/8UlWHLMpgZm9bx6QYh0NFoq67TZ.jpg"
        ]
    },
    # 19. DC Universe: Easter Eggs & Multiverse Theories
    {
        "id": 999202,
        "title": "DC Universe Secrets & Theories",
        "original_title": "DC Universe Easter Eggs & Theories",
        "slug": "dc-easter-eggs-theories",
        "media_type": "movie",
        "release_date": "2022-03-04",
        "hook_title": "DC Universe Secrets: 5 Dark Easter Eggs & Multiverse Theories 🦇🃏",
        "catchy_teaser": "Arkham riddles and James Gunn's DCU reboot! 5 dark easter eggs and shocking villain theories.",
        "overview": "Explore the hidden clues lurking in Gotham's shadows: Barry Keoghan's Joker cipher, Court of Owls architectural easter eggs, and James Gunn's roadmap for Gods and Monsters.",
        "tagline": "Unmask the truth.",
        "genres": ["Crime", "Mystery", "Action"],
        "runtime": 155,
        "seasons": None,
        "vote_average": 8.3,
        "vote_count": 12800,
        "category": "theories_easter_eggs",
        "director": "Matt Reeves & James Gunn",
        "top_cast": ["Robert Pattinson", "Colin Farrell", "Barry Keoghan", "Zoë Kravitz"],
        "poster_path": "/74xTEgt7R36Fpooo50r9T25onhq.jpg",
        "backdrop_path": "/eNGqhebQ4cDssjVeNFrKtUvweV5.jpg",
        "backdrops": [
            "/eNGqhebQ4cDssjVeNFrKtUvweV5.jpg",
            "/5UANyM4co2nwYPgSEmGeNlZRm7V.jpg"
        ]
    },
    # 20. Spider-Man & Venom: Post-Credit Clues
    {
        "id": 634649,
        "title": "Spider-Man & Venom Post-Credits",
        "original_title": "Spider-Man & Venom Multiverse",
        "slug": "spiderman-venom-post-credits",
        "media_type": "movie",
        "release_date": "2021-12-17",
        "hook_title": "Spider-Man & Venom: 5 Post-Credit Clues Connecting The Multiverse 🕷️🖤",
        "catchy_teaser": "The symbiote left behind in the MCU bar! 5 jaw-dropping Spider-Man & Venom post-credit secrets.",
        "overview": "When Eddie Brock and Venom left a droplet of alien symbiote on an MCU bar counter, Marvel altered the multiverse forever. Here is the full breakdown of Phase 6 clues.",
        "tagline": "The multiverse unleashed.",
        "genres": ["Action", "Adventure", "Science Fiction"],
        "runtime": 148,
        "seasons": None,
        "vote_average": 8.4,
        "vote_count": 22000,
        "category": "theories_easter_eggs",
        "director": "Jon Watts",
        "top_cast": ["Tom Holland", "Tom Hardy", "Zendaya", "Benedict Cumberbatch"],
        "poster_path": "/ui8e4sgZAwMPi3hzEO53jyBJF9B.jpg",
        "backdrop_path": "/53YhaL4xw4Sb1ssoHkeSSBaO29c.jpg",
        "backdrops": [
            "/53YhaL4xw4Sb1ssoHkeSSBaO29c.jpg",
            "/zD8Nsy4Xrghp7WunwpCj5JKBPeU.jpg"
        ]
    },
    # 21. Friends: Where Are They Now?
    {
        "id": 1668,
        "title": "Friends: Where Are They Now?",
        "original_title": "Friends Sitcom Cast Retrospective",
        "slug": "friends-where-are-they-now",
        "media_type": "tv",
        "release_date": "1994-09-22",
        "hook_title": "Friends: Where Are The Central Perk Stars Today? ☕✨",
        "catchy_teaser": "Could they BE any more iconic? From Hollywood power players to heartfelt tributes—see where the Friends cast is now!",
        "overview": "Thirty years after the premiere of Friends, discover what happened to Jennifer Aniston, Courteney Cox, Lisa Kudrow, Matt LeBlanc, David Schwimmer, and the lasting legacy of Matthew Perry.",
        "tagline": "I'll be there for you.",
        "genres": ["Comedy", "Romance", "Drama"],
        "runtime": 22,
        "seasons": 10,
        "vote_average": 8.5,
        "vote_count": 21000,
        "category": "where_are_they_now",
        "director": "David Crane & Marta Kauffman",
        "top_cast": ["Jennifer Aniston", "Courteney Cox", "Lisa Kudrow", "Matt LeBlanc", "David Schwimmer", "Matthew Perry"],
        "poster_path": "/cSOORhCRPJiwKghozXVXrOBi3Tp.jpg",
        "backdrop_path": "/vqjRBbuqXOvalAx5JZEaWx6kQOw.jpg",
        "backdrops": [
            "/vqjRBbuqXOvalAx5JZEaWx6kQOw.jpg",
            "/AtLnAEZMNzVMy07aG7QTVtfenj2.jpg"
        ]
    },
    # 22. The Office: Where Are They Now?
    {
        "id": 2316,
        "title": "The Office: Where Are They Now?",
        "original_title": "The Office (US) Cast Retrospective",
        "slug": "the-office-where-are-they-now",
        "media_type": "tv",
        "release_date": "2005-03-24",
        "hook_title": "The Office: Where Is The Dunder Mifflin Cast In 2026? 📄📎",
        "catchy_teaser": "That's what she said! From Scranton paper salesmen to Oscar nominees and Hollywood directors.",
        "overview": "Explore the extraordinary post-Scranton careers of Steve Carell, John Krasinski, Rainn Wilson, Jenna Fischer, Angela Kinsey, and Mindy Kaling.",
        "tagline": "A comedy for anyone whose boss is an idiot.",
        "genres": ["Comedy"],
        "runtime": 22,
        "seasons": 9,
        "vote_average": 8.6,
        "vote_count": 23500,
        "category": "where_are_they_now",
        "director": "Greg Daniels",
        "top_cast": ["Steve Carell", "John Krasinski", "Rainn Wilson", "Jenna Fischer", "Mindy Kaling"],
        "poster_path": "/7DJKHzAi83BmQrWLrYYOqcoKfhR.jpg",
        "backdrop_path": "/qHFidnMcFqUWdMFyjmXufBlYckd.jpg",
        "backdrops": [
            "/qHFidnMcFqUWdMFyjmXufBlYckd.jpg",
            "/1O7ECkD4mOKAgMAbQADBpTKBzOP.jpg"
        ]
    },
    # 23. Popular 90s/2000s Sitcom Stars: Where Are They Now?
    {
        "id": 999301,
        "title": "90s/2000s Sitcom Stars: Where Are They Now?",
        "original_title": "Popular 90s & 2000s Sitcom Icons",
        "slug": "sitcom-stars-where-are-they-now",
        "media_type": "tv",
        "release_date": "2000-01-09",
        "hook_title": "Where Are They Now? 5 Popular 90s/2000s Sitcom Stars 📺✨",
        "catchy_teaser": "Frankie Muniz, Alfonso Ribeiro, Angus T. Jones! See what your favorite sitcom childhood icons are doing today.",
        "overview": "From child prodigies to professional racecar drivers and primetime hosts: uncovering the fascinating second acts of Frankie Muniz, Alfonso Ribeiro, Angus T. Jones, and Jaleel White.",
        "tagline": "Then versus now: the untold journeys.",
        "genres": ["Comedy", "Family"],
        "runtime": 24,
        "seasons": 7,
        "vote_average": 8.4,
        "vote_count": 7800,
        "category": "where_are_they_now",
        "director": "Linwood Boomer",
        "top_cast": ["Frankie Muniz", "Alfonso Ribeiro", "Angus T. Jones", "Jaleel White", "Topher Grace"],
        "poster_path": "/si3OheCrSpEyK2JUtZOThsZPUR4.jpg",
        "backdrop_path": "/n61EctuWbXK9QCIJyLt3eWSfqUu.jpg",
        "backdrops": [
            "/n61EctuWbXK9QCIJyLt3eWSfqUu.jpg",
            "/qQFFEmt6Id9Nh4ckWx7FPlj2xah.jpg"
        ]
    },
    # 24. Fifty Shades of Grey
    {
        "id": 216015,
        "title": "Fifty Shades of Grey",
        "original_title": "Fifty Shades of Grey",
        "slug": "fifty-shades-of-grey",
        "media_type": "movie",
        "release_date": "2015-02-11",
        "hook_title": "Fifty Shades: 5 Untold Secrets Behind Christian Grey's Empire 🖤🔥",
        "catchy_teaser": "A $570M box office shockwave. 5 behind-the-scenes secrets of Hollywood's boldest modern romance.",
        "overview": "Literature student Anastasia Steele's life changes forever when she interviews enigmatic billionaire Christian Grey, plunging into a complex world of luxury, control, and intense passion.",
        "tagline": "Mr. Grey will see you now.",
        "genres": ["Drama", "Romance", "Thriller"],
        "runtime": 125,
        "seasons": None,
        "vote_average": 5.9,
        "vote_count": 12400,
        "category": "steamy_thrillers",
        "director": "Sam Taylor-Johnson",
        "top_cast": ["Dakota Johnson", "Jamie Dornan", "Jennifer Ehle", "Eloise Mumford", "Rita Ora"],
        "poster_path": "/63kGofUkt1Mx0SIL4XI4Z5AoSgt.jpg",
        "backdrop_path": "/7IGKrY1f1KfwMipx9wZC4NRgIdF.jpg",
        "backdrops": [
            "/7IGKrY1f1KfwMipx9wZC4NRgIdF.jpg",
            "/63kGofUkt1Mx0SIL4XI4Z5AoSgt.jpg"
        ]
    },
    # 25. 365 Days
    {
        "id": 664413,
        "title": "365 Days",
        "original_title": "365 Dni",
        "slug": "365-days",
        "media_type": "movie",
        "release_date": "2020-02-07",
        "hook_title": "365 Days: Why Netflix's Bold Sensation Broke Global Records 🔥💥",
        "catchy_teaser": "1 Year. 1 Demanding Sicilian Mob Boss. The global streaming hit that dominated #1 charts in 90+ countries.",
        "overview": "When sales director Laura is abducted in Sicily by mob boss Massimo Torricelli, she is given exactly 365 days to fall in love with him in a whirlwind of Mediterranean intrigue.",
        "tagline": "Are you lost baby girl?",
        "genres": ["Drama", "Romance", "Thriller"],
        "runtime": 114,
        "seasons": None,
        "vote_average": 5.6,
        "vote_count": 8900,
        "category": "steamy_thrillers",
        "director": "Barbara Białowąs",
        "top_cast": ["Michele Morrone", "Anna-Maria Sieklucka", "Bronisław Wrocławski", "Otar Saralidze"],
        "poster_path": "/6KwrHucIE3CvNT7kTm2MAlZ4fYF.jpg",
        "backdrop_path": "/29mZ5bR5m2w3xuvwJH7BHMFQQwH.jpg",
        "backdrops": [
            "/29mZ5bR5m2w3xuvwJH7BHMFQQwH.jpg",
            "/6KwrHucIE3CvNT7kTm2MAlZ4fYF.jpg"
        ]
    },
    # 26. Basic Instinct
    {
        "id": 402,
        "title": "Basic Instinct",
        "original_title": "Basic Instinct",
        "slug": "basic-instinct",
        "media_type": "movie",
        "release_date": "1992-03-20",
        "hook_title": "Basic Instinct: 5 Mind-Games That Defined The Erotic Thriller 🧊⚡",
        "catchy_teaser": "The infamous interrogation scene, ice-pick mind games, and Paul Verhoeven's boundary-pushing masterpiece.",
        "overview": "Detective Nick Curran investigates the brutal ice-pick murder of a rock star, becoming entangled with Catherine Tramell, an enigmatic novelist whose books eerily predict real-life crimes.",
        "tagline": "A brutal murder. A brilliant killer. A cop who can't resist.",
        "genres": ["Thriller", "Mystery"],
        "runtime": 128,
        "seasons": None,
        "vote_average": 6.9,
        "vote_count": 3800,
        "category": "steamy_thrillers",
        "director": "Paul Verhoeven",
        "top_cast": ["Michael Douglas", "Sharon Stone", "George Dzundza", "Jeanne Tripplehorn"],
        "poster_path": "/76Ts0yoHk8kVQj9MMnoMixhRWoh.jpg",
        "backdrop_path": "/7FRraud59N3s10bbf9bfYjvwx3v.jpg",
        "backdrops": [
            "/7FRraud59N3s10bbf9bfYjvwx3v.jpg",
            "/76Ts0yoHk8kVQj9MMnoMixhRWoh.jpg"
        ]
    },
    # 27. Saltburn
    {
        "id": 930564,
        "title": "Saltburn",
        "original_title": "Saltburn",
        "slug": "saltburn",
        "media_type": "movie",
        "release_date": "2023-11-17",
        "hook_title": "Saltburn: 5 Twisted Mind Games & Shocking Estate Secrets 🏰🍷",
        "catchy_teaser": "Obsession, luxury, and betrayal. The shocking psychological thriller that turned social media upside down.",
        "overview": "Oxford student Oliver Quick is invited by aristocratic classmate Felix Catton to Saltburn, his eccentric family's lavish estate, setting off a provocative summer of seduction and deceit.",
        "tagline": "We're all about to lose our minds.",
        "genres": ["Drama", "Comedy", "Thriller"],
        "runtime": 131,
        "seasons": None,
        "vote_average": 7.1,
        "vote_count": 3100,
        "category": "steamy_thrillers",
        "director": "Emerald Fennell",
        "top_cast": ["Barry Keoghan", "Jacob Elordi", "Rosamund Pike", "Richard E. Grant", "Carey Mulligan"],
        "poster_path": "/zGTfMwG112BC66mpaveVxoWPOaB.jpg",
        "backdrop_path": "/bAtFhmRHp0f6aHqj1UGTZoPcmQo.jpg",
        "backdrops": [
            "/bAtFhmRHp0f6aHqj1UGTZoPcmQo.jpg",
            "/zGTfMwG112BC66mpaveVxoWPOaB.jpg"
        ]
    },
    # 28. Oppenheimer
    {
        "id": 872585,
        "title": "Oppenheimer",
        "original_title": "Oppenheimer",
        "slug": "oppenheimer",
        "media_type": "movie",
        "release_date": "2023-07-21",
        "hook_title": "Trinity Detonation: 5 Mind-Blowing Secrets of Oppenheimer 💥☢️",
        "catchy_teaser": "Zero CGI used for the atomic blast. Inside Christopher Nolan's Oscar-sweeping historical masterpiece.",
        "overview": "The gripping story of J. Robert Oppenheimer's role in the development of the atomic bomb during World War II and the harrowing moral and political fallout that followed.",
        "tagline": "The world forever changes.",
        "genres": ["Drama", "History"],
        "runtime": 181,
        "seasons": None,
        "vote_average": 8.1,
        "vote_count": 9200,
        "category": "cult_classic",
        "director": "Christopher Nolan",
        "top_cast": ["Cillian Murphy", "Emily Blunt", "Matt Damon", "Robert Downey Jr.", "Florence Pugh"],
        "poster_path": "/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg",
        "backdrop_path": "/rLb2cwF3Pazuxaj0sRXQ037tGI1.jpg",
        "backdrops": [
            "/rLb2cwF3Pazuxaj0sRXQ037tGI1.jpg",
            "/fm6KqXpk3M2HVveHwCrBSSBaO0V.jpg",
            "/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg"
        ]
    },
    # 29. Squid Game
    {
        "id": 93405,
        "title": "Squid Game",
        "original_title": "오징어 게임",
        "slug": "squid-game",
        "media_type": "tv",
        "release_date": "2021-09-17",
        "hook_title": "Red Light, Green Light: 5 Twisted Rules of Squid Game 🔴🟢",
        "catchy_teaser": "456 desperate players. 45.6 Billion Won prize. One survivor. Inside Netflix's biggest global show ever.",
        "overview": "Hundreds of cash-strapped players accept a strange invitation to compete in children's games. Inside, a tempting prize awaits with deadly high stakes.",
        "tagline": "45.6 Billion Won is Child's Play.",
        "genres": ["Action & Adventure", "Mystery", "Drama"],
        "runtime": 55,
        "seasons": 2,
        "vote_average": 7.8,
        "vote_count": 14500,
        "category": "series",
        "director": "Hwang Dong-hyuk",
        "top_cast": ["Lee Jung-jae", "Park Hae-soo", "Wi Ha-joon", "Jung Ho-yeon", "Lee Byung-hun"],
        "poster_path": "/dDlEmu3EZ0Pgg93K2SVNLCjCSvE.jpg",
        "backdrop_path": "/soQgquPkLmUu9eKLJJzuA4KZDyi.jpg",
        "backdrops": [
            "/soQgquPkLmUu9eKLJJzuA4KZDyi.jpg",
            "/dDlEmu3EZ0Pgg93K2SVNLCjCSvE.jpg"
        ]
    },
    # 30. The Last of Us
    {
        "id": 100088,
        "title": "The Last of Us",
        "original_title": "The Last of Us",
        "slug": "the-last-of-us",
        "media_type": "tv",
        "release_date": "2023-01-15",
        "hook_title": "Endure & Survive: 5 Cordyceps Secrets In The Last of Us 🍄🧟",
        "catchy_teaser": "When you're lost in the darkness, look for the light. Pedro Pascal and Bella Ramsey's survival epic.",
        "overview": "Twenty years after modern civilization has been destroyed, Joel, a hardened survivor, is hired to smuggle Ellie, a 14-year-old girl, out of an oppressive quarantine zone.",
        "tagline": "When you're lost in the darkness, look for the light.",
        "genres": ["Drama", "Sci-Fi & Fantasy", "Action & Adventure"],
        "runtime": 60,
        "seasons": 2,
        "vote_average": 8.6,
        "vote_count": 5200,
        "category": "series",
        "director": "Craig Mazin & Neil Druckmann",
        "top_cast": ["Pedro Pascal", "Bella Ramsey", "Gabriel Luna", "Anna Torv", "Nick Offerman"],
        "poster_path": "/1E5baAaEse26fej7uHcjOgEE2t2.jpg",
        "backdrop_path": "/uDgy6hyPd82kOHh6I95FLtLnj6p.jpg",
        "backdrops": [
            "/uDgy6hyPd82kOHh6I95FLtLnj6p.jpg",
            "/1E5baAaEse26fej7uHcjOgEE2t2.jpg"
        ]
    },
    # 31. Twisters
    {
        "id": 718821,
        "title": "Twisters",
        "original_title": "Twisters",
        "slug": "twisters",
        "media_type": "movie",
        "release_date": "2024-07-19",
        "hook_title": "Rodeo Wranglers vs EF5 Monsters: 5 Wild Twisters Secrets 🌪️⚡",
        "catchy_teaser": "If you feel it, chase it! How Glen Powell and Daisy Edgar-Jones tackled real tornado-force fury.",
        "overview": "As storm season intensifies, the paths of a retired tornado chaser and a reckless social-media superstar collide as terrifying multiple storm systems converge over Oklahoma.",
        "tagline": "If you feel it, chase it.",
        "genres": ["Action", "Adventure", "Drama"],
        "runtime": 122,
        "seasons": None,
        "vote_average": 7.0,
        "vote_count": 1800,
        "category": "trending",
        "director": "Lee Isaac Chung",
        "top_cast": ["Daisy Edgar-Jones", "Glen Powell", "Anthony Ramos", "Brandon Perea", "David Corenswet"],
        "poster_path": "/pjnD08FlMAIXsfOLKQbvmO0f0MD.jpg",
        "backdrop_path": "/58D6ZAvOKxlHjyX9S8qNKSBE9Y.jpg",
        "backdrops": [
            "/58D6ZAvOKxlHjyX9S8qNKSBE9Y.jpg",
            "/pjnD08FlMAIXsfOLKQbvmO0f0MD.jpg"
        ]
    },
    # 32. Poor Things
    {
        "id": 792307,
        "title": "Poor Things",
        "original_title": "Poor Things",
        "slug": "poor-things",
        "media_type": "movie",
        "release_date": "2023-12-08",
        "hook_title": "Bella Baxter's Odyssey: 5 Bizarre Secrets of Poor Things 🦢🎩",
        "catchy_teaser": "Emma Stone's Oscar-winning tour-de-force! Inside Yorgos Lanthimos's wildly surreal cinematic wonder.",
        "overview": "Brought back to life by an unorthodox scientist, a young woman runs off with a debauched lawyer on a whirlwind adventure across continents, free from prejudices of her times.",
        "tagline": "She's like nothing you've ever seen.",
        "genres": ["Sci-Fi", "Romance", "Comedy"],
        "runtime": 141,
        "seasons": None,
        "vote_average": 7.8,
        "vote_count": 4100,
        "category": "trending",
        "director": "Yorgos Lanthimos",
        "top_cast": ["Emma Stone", "Mark Ruffalo", "Willem Dafoe", "Ramy Youssef", "Christopher Abbott"],
        "poster_path": "/kCGlIMHnOm8JPXq3rXM6c5wMxcT.jpg",
        "backdrop_path": "/bQS43HSLZzMjZkcHJz4fGc7fNdz.jpg",
        "backdrops": [
            "/bQS43HSLZzMjZkcHJz4fGc7fNdz.jpg",
            "/kCGlIMHnOm8JPXq3rXM6c5wMxcT.jpg"
        ]
    },
    # 33. Shōgun
    {
        "id": 126308,
        "title": "Shōgun",
        "original_title": "Shōgun",
        "slug": "shogun",
        "media_type": "tv",
        "release_date": "2024-02-27",
        "hook_title": "Master of Deception: 5 Epic Feudal Power Plays in Shōgun ⚔️🏯",
        "catchy_teaser": "Record-shattering 18 Emmy wins! Hiroyuki Sanada's historic political drama that captivated the world.",
        "overview": "When a mysterious European ship is found marooned in a nearby fishing village, Lord Yoshii Toranaga discovers secrets that could tip the scales of power and devastate his enemies.",
        "tagline": "Fate is a matter of choice.",
        "genres": ["Drama", "War & Politics"],
        "runtime": 60,
        "seasons": 1,
        "vote_average": 8.5,
        "vote_count": 1300,
        "category": "streaming_charts",
        "director": "Justin Marks & Rachel Kondo",
        "top_cast": ["Hiroyuki Sanada", "Cosmo Jarvis", "Anna Sawai", "Tadanobu Asano", "Takehiro Hira"],
        "poster_path": "/7O4iVfOMQmdCSxhOg1WnzG1AgYT.jpg",
        "backdrop_path": "/7O4iVfOMQmdCSxhOg1WnzG1AgYT.jpg",
        "backdrops": [
            "/7O4iVfOMQmdCSxhOg1WnzG1AgYT.jpg"
        ]
    }
]

SAMPLE_MOVIES = SAMPLE_MEDIA

